# Generated by Django 3.1.3 on 2021-01-16 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='شهر')),
            ],
            options={
                'ordering': ['state'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='استان')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('national_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کد ملی')),
                ('smart_card_number', models.CharField(max_length=5, verbose_name='شماره کارت هوشمند')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('family', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('cellnumber', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیکی')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاربخ ثبت نام')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='registration.city')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.state'),
        ),
    ]
