# Generated by Django 3.1.3 on 2021-01-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_driverinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverinfo',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
