# Generated by Django 3.1.5 on 2021-01-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210117_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverinfo',
            options={'ordering': ['national_id']},
        ),
    ]
