# Generated by Django 3.1.5 on 2021-02-02 07:30

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210125_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['state'], 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='driverinfo',
            options={'ordering': ['national_id'], 'verbose_name_plural': 'لیست اسامی'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name_plural': 'استان ها'},
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='national_id',
            field=models.CharField(error_messages={'unique': 'این کد ملی قبلا ثبت شده است'}, max_length=10, primary_key=True, serialize=False, unique=True, validators=[registration.models.validate_nid], verbose_name='کد ملی'),
        ),
    ]
